apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-pvc
  namespace: vsns
  labels:
    app: code-server
    environment: workshop
spec:
  storageClassName: do-block-storage-retain
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
