networks:
  mynet:
    driver: bridge

volumes:
  mydb_data:

services:
  mydb:
    image: stackupiss/northwind-db:v1
    container_name: mydb
    networks:
      - mynet
    volumes:
      - mydb_data:/var/lib/mysql

  myapp:
    image: stackupiss/northwind-app:v1
    container_name: myapp
    ports:
      - "8080:3000"
    networks:
      - mynet
    environment:
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: changeit
    depends_on:
      - mydb
